### ISSUE TITLE
Can't find the KafkaItemReader

### ISSUE THREAD

**Issue by SherlockLiang** [mouellet/spring-batch-kafka-sample#1]
Hi dear,

Would like to ask a question. I can't find the class object of KafkaItemReader in the spring batch v4.1.0-BUILD-SNAPSHOT. Could you please help to advise?

**Comment by mouellet** [comment]
Dear @SherlockLiang,

You would find that in this pull request: https://github.com/spring-projects/spring-batch/pull/664. It's still open and a work in progress, but the folks at spring-batch have this planned for the 4.2 release.. So stay tuned!
